package acs.boundaries;

import java.util.Date;
import java.util.Map;

import acs.boundaries.data.Element;
import acs.boundaries.data.Invoker;

/**
 * 
 * This class mediates between the user's input to the server's logic
 *
 */
public class ActionBoundary {
	/**
	 * Various attributes of an action boundary
	 */
	private String actionId; 
	private String type; 
	private Element element; 
	private Date createdTimestamp;
	private Invoker invokedBy; 
	private Map<String, Object> actionAttributes;

	public ActionBoundary() {

	}

	   /**
	   * Creates an action boundary with the user's input from the RequestBody
	   * 
	   * @param actionId This ID is generated by the database
	   * @param type This is the type of action 
	   * @param element This is the element that the action invoked on
	   * @param createdTimestamp The date and time the action is created
       * @param invokedBy The is the user that invokes the action
	   * @param actionAttributes These are extra attributes that may be added to the action
	   */
	public ActionBoundary(String actionId, String type, Element element, Date createdTimestamp, Invoker invokedBy,
			Map<String, Object> actionAttributes) {
		super();
		this.actionId = actionId;
		this.type = type;
		this.element = element;
		this.createdTimestamp = createdTimestamp;
		this.invokedBy = invokedBy;
		this.actionAttributes = actionAttributes;
	}
	/**
     * @return the action's ID
     */
	public String getActionId() {
		return actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}
	
	/**
     * @return the action's type
     */
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	/**
     * @return the element which has the element's id that the action is invoked on
     */
	public Element getElement() {
		return element;
	}

	public void setElement(Element element) {
		this.element = element;
	}

	/**
     * @return the action's created time-stamp
     */
	public Date getCreatedTimestamp() {
		return createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}
	/**
     * @return the action's invoker
     */
	public Invoker getInvokedBy() {
		return invokedBy;
	}

	public void setInvokedBy(Invoker invokedBy) {
		this.invokedBy = invokedBy;
	}
	
	/**
     * @return the action's attributes
     */
	public Map<String, Object> getActionAttributes() {
		return actionAttributes;
	}

	public void setActionAttributes(Map<String, Object> actionAttributes) {
		this.actionAttributes = actionAttributes;
	}

	@Override
	public String toString() {
		return "ActionBoundary [actionId=" + actionId + ", type=" + type + ", element=" + element + "]";
	}

}
